{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-github-actions
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: User
    name: {{ .Values.rbac.githubUser }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .Values.rbac.roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
